"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var _findIndex = require("lodash/findIndex");
var _find = require("lodash/find");
var _findLast = require("lodash/findLast");
var _groupBy = require("lodash/groupBy");
var _sum = require("lodash/sum");
var _filter = require("lodash/filter");
var _remove = require("lodash/remove");
var _pullAt = require("lodash/pullAt");
var _pull = require("lodash/pull");
var _chunk = require("lodash/chunk");
var _uniq = require("lodash/uniq");
var _uniqBy = require("lodash/uniqBy");
var arrayHp;
(function (arrayHp) {
    arrayHp.isArray = function (obj) {
        return obj instanceof Array;
    };
    arrayHp.findIndex = _findIndex;
    arrayHp.find = _find;
    arrayHp.findLast = _findLast;
    arrayHp.groupBy = _groupBy;
    arrayHp.sum = _sum;
    arrayHp.filter = _filter;
    arrayHp.remove = _remove;
    arrayHp.pullAt = _pullAt;
    arrayHp.pull = _pull;
    arrayHp.chunk = _chunk;
    arrayHp.uniq = _uniq;
    arrayHp.uniqBy = _uniqBy;
})(arrayHp = exports.arrayHp || (exports.arrayHp = {}));
